import { MealType } from './enums';

export interface WeeklyPlan {
  id: string;
  userId: string;
  
  // Plan details
  weekStartDate: Date; // Monday of the week
  weekEndDate: Date; // Sunday of the week
  title?: string; // Optional custom title
  description?: string;
  
  // Meals for the week
  meals: PlannedMeal[];
  
  // Planning metadata
  peopleCount: number; // Number of people this plan serves
  budget?: number; // Optional budget for the week
  
  // Sharing
  isShared: boolean;
  sharedWith: string[]; // Array of user IDs
  sharedByUserId?: string; // If this plan was shared by someone else
  
  // Auto-generation settings
  autoGenerated: boolean;
  preferences?: PlanningPreferences;
  
  // Status
  isActive: boolean; // Current active plan
  completed: boolean;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

export interface PlannedMeal {
  id: string;
  date: Date;
  mealType: MealType;
  recipeId: string;
  
  // Denormalized recipe data for performance
  recipeName: string;
  recipeImageUrl?: string;
  recipeCookTime: number;
  recipeServings: number;
  
  // Customization for this meal
  servings: number; // Adjusted servings for this meal
  notes?: string;
  
  // Status
  completed: boolean;
  completedAt?: Date;
  
  // Preparation
  prepDay?: Date; // If meal prep is needed
  leftoverPortions?: number;
}

export interface PlanningPreferences {
  maxCookTimePerMeal: number;
  preferredCuisines: string[];
  avoidRepeating: boolean; // Avoid same recipe in same week
  balancedNutrition: boolean;
  budgetAware: boolean;
  mealPrepFriendly: boolean;
  quickMealsOnWeekdays: boolean;
  
  // Meal type preferences
  mealTypePreferences: {
    [MealType.BREAKFAST]: MealTypePreference;
    [MealType.LUNCH]: MealTypePreference;
    [MealType.DINNER]: MealTypePreference;
    [MealType.SNACK]: MealTypePreference;
  };
}

export interface MealTypePreference {
  enabled: boolean;
  maxCookTime: number;
  preferredCategories: string[];
  maxCalories?: number;
}

// For weekly plan templates
export interface WeeklyPlanTemplate {
  id: string;
  name: string;
  description: string;
  authorId: string;
  
  // Template structure
  mealStructure: TemplateMeal[];
  
  // Metadata
  difficulty: string; // beginner, intermediate, advanced
  cuisine: string;
  dietary: string[]; // vegetarian, keto, etc.
  estimatedCost: number;
  prepTime: number;
  
  // Social
  uses: number; // How many times it's been used
  rating: number;
  isPublic: boolean;
  
  createdAt: Date;
  updatedAt: Date;
}

export interface TemplateMeal {
  dayOfWeek: number; // 0-6 (Sunday-Saturday)
  mealType: MealType;
  recipeId?: string; // Optional specific recipe
  recipeCategory?: string; // Or just a category suggestion
  maxCookTime?: number;
  notes?: string;
}